version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    dependencies:
      pre:
        - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        - sudo apt-get update -qq
        - sudo apt-get install -y ttf-mscorefonts-installer
        - sudo fc-cache -fv
    steps:
      - checkout
      - run: npm install
      - run: npm test
